update gitignore, refacto, improve collaborons page
ansforge/IG-documentation pull request #37
Opened 2023-10-17 09:21 UTC by nriss

2023-10-17 12:02 UTC, sdemeyANS commented on .gitignore
> +local-template/*
obligé de mettre les 2 lignes?

2023-10-17 12:04 UTC, sdemeyANS commented on input/pagecontent/bonnes_pratiques_implementer.md
> +Des serveurs FHIR open source (ex: [HAPI](https://hapifhir.io)) permettent de développer simplement une API FHIR supportant déjà la plupart des fonctionnalités (SearchParameter, Operation ...).
je cherche la diff :)

2023-10-17 12:11 UTC, nriss commented on .gitignore
> +local-template/*
Remplacé par une ligne local-template*

2023-10-17 12:44 UTC, sdemeyANS requested changes

2023-10-17 12:44 UTC, sdemeyANS commented on input/pagecontent/collaborons.md
> +N'importe qui a la possibilité de créer des guides d'implémentation FHIR qui a pour vocation d'intégrer le CI-SIS. On parlera ainsi d'Unité de Production (UP) externe.
plutôt parler d'ouverture ?

2023-10-17 12:44 UTC, sdemeyANS commented on input/pagecontent/tests.md
> +* EVSClient, qui permet de vérifier la conformité : des documents CDA, des archives IHE_XDM.ZIP utilisés pour les échanges, des ressources FHIR...
des archives ... utiliséEs ?

2023-10-17 14:39 UTC, sdemeyANS approved these changes

2023-10-20 07:39 UTC, sdemeyANS commented on input/pagecontent/bonnes_pratiques_modeler.md
> +Pour préciser le statut de maturité, il est possible de préciser la maturité sous forme de release notes en début de page index en utilisant la balise \<blockquote class=\"stu-note\"\>\<blockquote\>.
👍

2023-10-20 07:40 UTC, sdemeyANS approved these changes
merci :)

2023-10-20 08:03 UTC, sdemeyANS approved these changes

2023-10-20 08:30 UTC, TristanKEREVAL approved these changes

2023-10-20 12:13 UTC, paulineheurtebise commented on input/pagecontent/bonnes_pratiques_modeler.md
> +> releaseLabel: STU1
Est ce qu'ici aussi ca doit etre "trial-use" ?

2023-10-20 12:19 UTC, nriss commented on input/pagecontent/bonnes_pratiques_modeler.md
> +> releaseLabel: STU1
Corrigé, merci :)

2023-10-20 12:39 UTC, mbrulliard commented on input/pagecontent/bonnes_pratiques_modeler.md
> +A l'heure actuelle, les spécifications des projets nationaux utilisent la R4 (fr-core, IG ANS, Annuaire, ROR...).  Or travailler sur R4 et R5 parallèlement engendre beaucoup de questions : travaux de
Pourquoi parler de CDA ici ?

2023-10-20 12:39 UTC, mbrulliard commented on input/pagecontent/bonnes_pratiques_modeler.md
> +En conclusion : privilégier R4 pour ne pas être "hors système" et être cohérent avec fr-core et les IGs de l'ANS tant qu'il n'y a pas de socle commun à l'utilisation de R5. Utiliser R5 uniquement si
Peut-être préciser que c'est la conclusion aujourd'hui ? (puisque comme tu viens de le dire au dessus le sujet reste ouvert à la discussion)
Et peut-être mettre cette phrase en fin de conclusion : A noter que FHIR R6, dont la première concertation est prévue mi-2024, apportera beaucoup de contenu normatif, et sera peut-être l'objectif de transition.

2023-10-20 12:39 UTC, mbrulliard commented on input/pagecontent/collaborons.md
> +* les profils fr core et annuaire santé, très génériques doivent être systématiquement hérités et utilisés en France;
La formulation m'embête : ce sont tous les profils projet qui doivent hériter des profils fr-core et annuaire, non ?

2023-10-20 12:39 UTC, mbrulliard commented on input/pagecontent/tests.md
> +* Gazelle, qui permet de tester des scénarios complets avec plusieurs interactions d'échanges de données.
Gazelle Test Management

2023-10-20 12:44 UTC, nriss commented on input/pagecontent/bonnes_pratiques_modeler.md
> +A l'heure actuelle, les spécifications des projets nationaux utilisent la R4 (fr-core, IG ANS, Annuaire, ROR...).  Or travailler sur R4 et R5 parallèlement engendre beaucoup de questions : travaux de
Si quelqu'un souhaite faire du mapping CDA --> FHIR, il faudra maintenir :
- CDA --> FHIR R4
- CDA --> FHIR R5
- etc

2023-10-20 12:46 UTC, nriss commented on input/pagecontent/collaborons.md
> +* les profils fr core et annuaire santé, très génériques doivent être systématiquement hérités et utilisés en France;
Qu'entends-tu par profil projet ? A mon sens, ça doit être tous les profils français qui doivent hériter de FrCore et de l'annuaire (ci-sis, implémentation éditeurs, projet ANS, etc ...)

2023-10-20 12:46 UTC, nriss commented on input/pagecontent/tests.md
> +* Gazelle, qui permet de tester des scénarios complets avec plusieurs interactions d'échanges de données.
Merci pour tes retours, j'ai mis à jour le contenu :)

2023-10-20 13:54 UTC, mbrulliard commented on input/pagecontent/collaborons.md
> +* les profils fr core et annuaire santé, très génériques doivent être systématiquement hérités et utilisés en France;
Je suis d'accord sur le fond évidemment, c'est juste la formulation : "les profils fr-core en annuaire doivent être hérités" ; pour moi ce sont les profils de chaque projet qui doivent hériter de fr-core et annuaire mais je ne crois pas que ça se dise "les profils doivent être hérités".
Je trouve que ça porte à confusion mais si c'est un détail, n'en tiens pas compte !

2023-10-20 14:13 UTC, nriss commented on input/pagecontent/collaborons.md
> +* les profils fr core et annuaire santé, très génériques doivent être systématiquement hérités et utilisés en France;
J'ai amélioré la tournure, dis-moi si c'est plus clair :)

2023-10-20 14:23 UTC, mbrulliard commented on input/pagecontent/bonnes_pratiques_modeler.md
> +En conclusion : privilégier R4 pour ne pas être "hors système" et être cohérent avec fr-core et les IGs de l'ANS tant qu'il n'y a pas de socle commun à l'utilisation de R5. Utiliser R5 uniquement si
je trouve ça clair !

2023-10-20 14:24 UTC, mbrulliard commented on input/pagecontent/collaborons.md
> +* les profils fr core et annuaire santé, très génériques doivent être systématiquement hérités et utilisés en France;
Oui !

2023-10-24 13:57 UTC, merged