Nr add versioning advices
ansforge/IG-documentation pull request #39
Opened 2023-10-26 13:18 UTC by nriss

2023-10-26 13:24 UTC, M-Priour commented on input/pagecontent/bonnes_pratiques_implementer.md
> +* **Toujours** baser une implémentation sur une version spécifique d'un IG et donc d'un [package FHIR](https://hl7.org/fhir/packages.html) publié dans le [fhir package registry](https://registry.fhir
Est-ce que cela concerne toujours les serveurs ? Est-ce qu'il ne faudra pas mettre "solution" ou "logiciel" à la place?

2023-10-26 13:25 UTC, nriss commented on input/pagecontent/bonnes_pratiques_implementer.md
> +* **Toujours** baser une implémentation sur une version spécifique d'un IG et donc d'un [package FHIR](https://hl7.org/fhir/packages.html) publié dans le [fhir package registry](https://registry.fhir
Je suis d'accord!

2023-10-26 13:44 UTC, sdemeyANS requested changes

2023-10-27 13:15 UTC, nriss commented on input/pagecontent/bonnes_pratiques_implementer.md
> +* **Anticiper** les futures évolutions de l'API pour les rendre moins douloureuses. Pour cela, une des possibilité est de faire un mapping entre un modèle de base de données et une API FHIR. Lorsqu'u
Les implémentations doivent :
- Afficher la version de l'IG supporté
- Afficher quand est-ce que chaque version d'API sera deprecated

2023-10-30 18:53 UTC, merged