Update validate-resource with FHIR validator and matchbox
ansforge/IG-documentation pull request #44
Opened 2023-11-23 15:43 UTC by nriss

## Description des changements

* Mise à jour de la documentation sur la validation de ressources FHIR : ajout du validator officiel et de matchbox

## Preview

https://ansforge.github.io/IG-documentation/ig/nr-add-validator-link

2023-12-27 08:17 UTC, nriss commented
Hello, pourriez-vous me review cette PR ?

2023-12-27 08:29 UTC, M-Priour requested changes

2023-12-27 08:29 UTC, M-Priour commented on input/pagecontent/valider_res.md
> +* [https://test.ahdis.ch/matchbox]
On pourrait ajouter le validateur HL7 : https://validator.fhir.org/

2023-12-27 08:32 UTC, nriss commented on input/pagecontent/valider_res.md
> +* [https://test.ahdis.ch/matchbox]
Il y est à priori

2023-12-27 08:37 UTC, M-Priour commented on input/pagecontent/valider_res.md
> +* [https://test.ahdis.ch/matchbox]
Oups, pardon.

2024-01-02 09:58 UTC, sdemeyANS requested changes

2024-01-02 09:58 UTC, sdemeyANS commented on input/pagecontent/valider_res.md
> +* Le / les profils ne sont pas issus d'un contexte particulier et se présentent sous forme d'un ficher xml ou json (pratique à déconseillée)
typo => (pratique à déconseillée)

2024-01-08 14:04 UTC, nriss commented on input/pagecontent/valider_res.md
> +* Le / les profils ne sont pas issus d'un contexte particulier et se présentent sous forme d'un ficher xml ou json (pratique à déconseillée)
J'ai les yeux qui piquent

2024-01-30 16:53 UTC, nriss commented
Hello, pourriez-vous me review/valider cette PR ?

2024-01-30 17:11 UTC, M-Priour approved these changes

2024-01-30 17:54 UTC, sdemeyANS approved these changes

2024-01-31 14:13 UTC, merged