Refactoring pages
ansforge/IG-documentation pull request #66
Opened 2024-07-16 11:43 UTC by nriss

## Description des changements

* [changement 1]
* [changement 2]
* ...

## Preview

https://ansforge.github.io/IG-documentation/[ajouter_nom_de_la_branche]/ig

2024-10-23 10:05 UTC, sdemeyANS requested changes

2024-10-23 10:05 UTC, sdemeyANS commented on input/pagecontent/index.md
> +Un implementation guide se présente sous forme d'un site web et d'un package contenant l'ensemble des ressources de conformité. Les implementation guides (site web, ressources de conformité et packag
suggestion : mettre un point à la place de la virgule
", l'ensemble des versions historiques seront toujours accessibles."
=> ". L'ensemble des versions historiques seront toujours accessibles."

2024-10-23 10:05 UTC, sdemeyANS commented on input/pagecontent/index.md
>  * Les documentations génériques peuvent être surspécifiées pour réutiliser certains profils pour un autre cas d'usage, en héritant de tout ou partie, ou pour décrire une implémentation précise.
"point" en trop en fin de ligne 16?

2024-10-23 10:05 UTC, sdemeyANS commented on input/pagecontent/index.md
> +* L'IG doit obligatoirement hériter des profils FHIR réalisés par InteropSanté et/ou par l'ANS.
si ils existent

2025-02-21 16:43 UTC, sdemeyANS requested changes

2025-02-21 16:43 UTC, sdemeyANS commented on input/pagecontent/bonnes_pratiques_modeler.md
> +Ces règles de nommage ont été établies en s'inspirant des ressources us-core et des bonnes pratiques indiquées [ici](https://build.fhir.org/ig/HL7/crmi-ig/artifact-conventions.html).
l'url c'est une version ci-build. C'est normal?

2025-02-21 16:43 UTC, sdemeyANS commented on input/pagecontent/dev_nouvel_ig.md
> +Ce nouveau projet doit utiliser le GitHub template ansforge/IG-modele et doit être préfixé par "IG-...". Le repository GitHub doit être nommé de sorte  qu'il soit facilement retrouvé et compréhensibl
```suggestion
Ce nouveau projet doit utiliser le GitHub template ansforge/IG-modele et doit être préfixé par "IG-...". Le repository GitHub doit être nommé de sorte qu'il soit facilement retrouvé et compréhensible par n'importe qui : Descriptif, lisible, cohérent, contextuel, extensible, réutilisable, bref. Il doit être préfixé par "IG-"[...]. Exemple : IG-fhir-partage-de-documents-de-sante. N'hésitez pas à solliciter la team interopérabilité de l'ANS pour avis.
```

2025-02-21 16:43 UTC, sdemeyANS commented on input/pagecontent/dev_nouvel_ig.md
> +Ce nouveau projet doit utiliser le GitHub template ansforge/IG-modele et doit être préfixé par "IG-...". Le repository GitHub doit être nommé de sorte  qu'il soit facilement retrouvé et compréhensibl
: Descriptif => enlever la majuscule? faire une énumération pour aérer?

2025-02-21 16:43 UTC, sdemeyANS commented on input/pagecontent/dev_nouvel_ig.md
> +Ce nouveau projet doit utiliser le GitHub template ansforge/IG-modele et doit être préfixé par "IG-...". Le repository GitHub doit être nommé de sorte  qu'il soit facilement retrouvé et compréhensibl
Il doit être préfixé par "IG-"[...] => répétition de Ce nouveau projet doit utiliser le GitHub template ansforge/IG-modele et doit être préfixé par "IG-..." juste au dessus?

2025-02-21 16:45 UTC, nriss commented on input/pagecontent/bonnes_pratiques_modeler.md
> +Ces règles de nommage ont été établies en s'inspirant des ressources us-core et des bonnes pratiques indiquées [ici](https://build.fhir.org/ig/HL7/crmi-ig/artifact-conventions.html).
Corrigé

2025-02-21 16:58 UTC, sdemeyANS approved these changes

2025-02-21 17:05 UTC, merged